### ISSUE TITLE
Add russian translation

### ISSUE THREAD

**Issue by Donut05** [SMLeaks/website-new#17] opened 2022-04-15 19:05 UTC
Add translation to the website. I will provide the nececary material.
Reason: Russian community is the 2nd biggest in th world.
Peace, love Donut#9976 from sm leaks discord.

**Comment by Tofix26** [comment] 2022-04-15 19:07
yes

**Comment by trbodev** [comment] 2022-04-15 19:07
Duplicate of #3

**Closed by trbodev** 2022-04-15 19:07 UTC
